### ISSUE TITLE
Docs promote partial updates on Arch

### ISSUE THREAD

**Issue by hXtreme** [BetaPictoris/dict#10]
https://github.com/BetaPictoris/dict/blob/dev/docs/readme.md#L28

Partial updates are highly discouraged on Arch, it would be great if you could update the documentation to instead use `-Syu` options.

There's one more instance of this same issue with a command using `paru`.

**Comment by BetaPictoris** [comment]
5f1c93dcce67c301a12938d5db56d03f5a3d79e6: Fixed this issue, closing...
